NMS-13016: normalize error output for RUNAS validation

diff --git a/opennms-base-assembly/src/main/filtered/bin/generate-opennms-thread-dump b/opennms-base-assembly/src/main/filtered/bin/generate-opennms-thread-dump
--- a/opennms-base-assembly/src/main/filtered/bin/generate-opennms-thread-dump
+++ b/opennms-base-assembly/src/main/filtered/bin/generate-opennms-thread-dump
@@ -169,10 +169,12 @@ parseArgs "$@"
 
 myuser="$(id -u -n)"
 if [ "$myuser" = "$RUNAS" ]; then
-	true # all is well
+    true # all is well
 else
-	warn "FATAL: you must run this script as $RUNAS, not '$myuser'" >&2
-	exit 4	# According to LSB: 4 - user had insufficient privileges
+    echo "ERROR: you must run this script as ${RUNAS}, not '${myuser}'." >&2
+    echo "       Create or edit ${opennms_home}/etc/opennms.conf and set 'RUNAS=${myuser}'" >&2
+    echo "       if you wish for OpenNMS to run as ${myuser} instead." >&2
+    exit 4 # According to LSB: 4 - user had insufficient privileges
 fi
 
 find_jstack_bin
