NMS-14410: Minor fixes

diff --git a/opennms-base-assembly/src/main/filtered/bin/install b/opennms-base-assembly/src/main/filtered/bin/install
--- a/opennms-base-assembly/src/main/filtered/bin/install
+++ b/opennms-base-assembly/src/main/filtered/bin/install
@@ -29,10 +29,27 @@ if [ -f "$OPENNMS_HOME/etc/opennms.conf" ]; then
 	. "$OPENNMS_HOME/etc/opennms.conf"
 fi
 
+
+while getopts vcfhnpqrsS:j:a: c
+do
+  case $c in
+      x)
+          no_sudo=1
+          ;;
+
+      \?)
+          echo "Invalid option."
+          exit 1
+          ;;
+  esac
+done
+
 SUDO="$(command -v sudo 2>/dev/null || which sudo 2>/dev/null || :)"
 myuser="$(id -u -n)"
 if [ "$myuser" != "$RUNAS" ]; then
-	if [ "$myuser" = "root" ] && [ -n "$SUDO" ] && [ -x "$SUDO" ]; then
+    if [ $no_sudo ]; then
+        echo "WARNING: Running script as current user"
+	elif [ "$myuser" = "root" ] && [ -n "$SUDO" ] && [ -x "$SUDO" ]; then
 		echo "WARNING: relaunching as $RUNAS" >&2
 		_cmd=("$SUDO" "-u" "$RUNAS" "$0" "${INCOMING_ARGS[@]}");
 		exec "${_cmd[@]}"
@@ -58,7 +75,8 @@ for opt in $ADDITIONAL_MANAGER_OPTIONS; do
 	esac
 done
 
-if [ $no_sudo ]; then
+if [ $no_sudo ] && [ "$myuser" != "$RUNAS" ]; then
+    echo "Atytempting to run install as $myuser..."
     # shellcheck disable=SC2086
     "$OPENNMS_BINDIR"/runjava -r -- \
         $OPTIONS \
diff --git a/opennms-base-assembly/src/main/filtered/bin/upgrade b/opennms-base-assembly/src/main/filtered/bin/upgrade
--- a/opennms-base-assembly/src/main/filtered/bin/upgrade
+++ b/opennms-base-assembly/src/main/filtered/bin/upgrade
@@ -20,7 +20,8 @@ do
           ;;
 
       \?)
-          die "Invalid option."
+          echo "Invalid option."
+          exit 1
           ;;
   esac
 done
@@ -44,7 +45,8 @@ if [ "$myuser" != "$RUNAS" ]; then
 fi
 
 APP_CLASS=org.opennms.upgrade.support.Upgrade
-if [ $no_sudo ]; then
+if [ $no_sudo ] && [ "$myuser" != "$RUNAS" ]; then
+    echo "Attempting to run upgrade as $myuser..."
     # shellcheck disable=SC2086
     "$OPENNMS_HOME/bin/runjava" -r -- $JAVA_OPTIONS \
         -Dopennms.home="$OPENNMS_HOME" \
