NMS-4378 failure to connect to admin db on startup should be non-fatal

diff --git a/opennms-base-assembly/src/main/filtered/bin/opennms b/opennms-base-assembly/src/main/filtered/bin/opennms
--- a/opennms-base-assembly/src/main/filtered/bin/opennms
+++ b/opennms-base-assembly/src/main/filtered/bin/opennms
@@ -241,7 +241,7 @@ doStart(){
 
 	$JAVA_CMD -Dopennms.home=$OPENNMS_HOME -jar $BOOTSTRAP check
 	if [ $? -ne 0 ]; then
-		echo "OpenNMS runs better if you start up the database first." >&2
+		echo "OpenNMS was unable to connect to the 'opennms' database configured in opennms-datasources.xml." >&2
 		return 1
 	fi
 
