Add progress bar for startup and shutdown.

diff --git a/opennms-base-assembly/src/main/filtered/bin/opennms b/opennms-base-assembly/src/main/filtered/bin/opennms
--- a/opennms-base-assembly/src/main/filtered/bin/opennms
+++ b/opennms-base-assembly/src/main/filtered/bin/opennms
@@ -19,6 +19,12 @@ LOG_DIRECTORY="${install.logs.dir}"
 # Where to redirect "start" output.
 REDIRECT="$LOG_DIRECTORY/output.log"
 
+# Where the progress bar startup output goes
+PROGRESS_LOG="$LOG_DIRECTORY/progressbar.log"
+
+# Whether to show the progress bar
+PROGRESS_BAR=1
+
 # Number of times to do "opennms status" after starting OpenNMS to see
 # if it comes up completely.  Set to "0" to disable.  Between each
 # attempt we sleep for STATUS_WAIT seconds.
@@ -457,6 +463,11 @@ doStart(){
 		echo "running ulimit -a"
 		ulimit -a
 		runCmd "${CMD[@]}" &
+		if [ ${PROGRESS_BAR} -gt 0 ]; then
+			# XXX not sure of the right way to do this with systemd
+			# Assuming the process will be killed later by systemd.
+			tail -0F "${PROGRESS_LOG}" &
+		fi
 	else
 		if [ "$BACKGROUND" = 1 ]; then
 			# shellcheck disable=SC2129
@@ -484,22 +495,36 @@ doStart(){
 		return 0
 	fi
 
+	if [ ${PROGRESS_BAR} -gt 0 ]; then
+		tail -0F "${PROGRESS_LOG}" &
+		tail_pid=$!
+		trap "kill ${tail_pid} > /dev/null 2>&1" 0
+	fi
+
 	# wait for startup
 	STATUS_ATTEMPTS=0
 	while [ "$STATUS_ATTEMPTS" -lt "$START_TIMEOUT" ]; do
 		sleep $STATUS_WAIT
 		if doStatus "$@"; then
+			if [ ${PROGRESS_BAR} -gt 0 ]; then
+				kill ${tail_pid} > /dev/null 2>&1
+				trap "" 0
+			fi
 			return 0
 		fi
 		if isRunning "$(getPid)"; then
 			true		# Java process is still running... don't do anything
 		else
-			echo "Started ${install.package.description}, but it stopped running: for details see $REDIRECT" >&2
+			echo "Started ${install.package.description}, but it stopped running: see details above or $REDIRECT" >&2
 			return 1
 		fi
 		((STATUS_ATTEMPTS++))
 	done
 
+	if [ ${PROGRESS_BAR} -gt 0 ]; then
+		# Assume the progress bar hasn't completed so advance to the next line
+		echo ""
+	fi
 	echo "Started ${install.package.description}, but it has not finished starting up" >&2
 	return 1
 }
@@ -588,11 +613,21 @@ doStop() {
 		runCmd "${RUNJAVA_CMD[@]}" "${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
 	fi
 
+	if [ ${PROGRESS_BAR} -gt 0 ]; then
+		tail -0F "${PROGRESS_LOG}" &
+		tail_pid=$!
+		trap "kill ${tail_pid} > /dev/null 2>&1" 0
+	fi
+
 	STATUS_ATTEMPTS=0
 	while [ "$STATUS_ATTEMPTS" -lt "$STOP_TIMEOUT" ]; do
 		doStatus "$@"
 		if [ "$?" -eq 3 ]; then
 			clearPids
+			if [ ${PROGRESS_BAR} -gt 0 ]; then
+				kill ${tail_pid} > /dev/null 2>&1
+				trap "" 0
+			fi
 			return 0
 		fi
 
@@ -775,6 +810,11 @@ MANAGER_OPTIONS+=("-Dopennms.home=$OPENNMS_HOME")
 #MANAGER_OPTIONS+=("-Djcifs.properties=$OPENNMS_HOME/etc/jcifs.properties")
 MANAGER_OPTIONS+=("-XX:+HeapDumpOnOutOfMemoryError")
 
+MANAGER_OPTIONS+=("-Dopennms.name=${install.package.description}")
+columns=$(which tput > /dev/null 2>&1 && tput cols)
+if [ -n "${columns}" ]; then
+	MANAGER_OPTIONS+=("-Dterminal.columns=${columns}")
+fi
 
 if [ -n "$JAVA_INITIAL_HEAP_SIZE" ];then
  if [[ "$JAVA_INITIAL_HEAP_SIZE" =~ [0-9] ]];then
@@ -1036,10 +1076,12 @@ case "$COMMAND" in
 			fi
 			echo ""
 		else
-			if [ "$__ret" -eq 0 ]; then
-				echo "ok"
-			else
-				echo "failed"
+			if [ ${PROGRESS_BAR} -eq 0 ]; then
+				if [ "$__ret" -eq 0 ]; then
+					echo "ok"
+				else
+					echo "failed"
+				fi
 			fi
 		fi
 		exit "$__ret"
@@ -1071,7 +1113,9 @@ case "$COMMAND" in
 			echo ""
 		else
 			if [ "$__ret" -eq 0 ]; then
-				echo "stopped"
+				if [ ${PROGRESS_BAR} -eq 0 ]; then
+					echo "stopped"
+				fi
 			else
 				echo "failed"
 			fi
