Revert "Merge remote-tracking branch 'origin' into features/topology"
This reverts commit 3b3c99c1547bbd705efc4a74c612dbbc55de3564, reversing
changes made to 56974677f65d0eaaba5bdcf2e62e7acfde204e27.

diff --git a/opennms-base-assembly/src/main/filtered/bin/opennms b/opennms-base-assembly/src/main/filtered/bin/opennms
--- a/opennms-base-assembly/src/main/filtered/bin/opennms
+++ b/opennms-base-assembly/src/main/filtered/bin/opennms
@@ -18,11 +18,18 @@
 # Description:       ${install.package.description} daemon for network monitoring
 ### END INIT INFO
 #
+#  $Id$
+#
 #  For info on the "chkconfig:" section, see:
 #     http://www.sensi.org/~alec/unix/redhat/sysvinit.html
 #
 #  For info on the "BEGIN INIT INFO" section, see:
 #     http://www.suse.de/~mmj/Package-Conventions/
+#
+# Modifications:
+#
+# 2005 Oct 01: Removed `date` from a few echo commands and redirected
+#              a few error messages to stderr. -- DJ Gregor
 #
 
 #### ------------> DO NOT CHANGE VARIABLES IN THIS FILE <------------- ####
@@ -999,18 +1006,17 @@ if [ "$VERBOSE_GC" != "" ]; then
 	MANAGER_OPTIONS+=("-verbose:gc")
 fi
 
-RUNUSER="$(command -v runuser 2>/dev/null || which runuser 2>/dev/null || :)"
+SUDO="$(command -v sudo 2>/dev/null || which sudo 2>/dev/null || :)"
 myuser="$(id -u -n)"
 if [ "$myuser" != "$RUNAS" ]; then
-	if [ "$myuser" = "root" ] && [ -x "$RUNUSER" ]; then
+	if [ "$myuser" = "root" ] && [ -n "$SUDO" ] && [ -x "$SUDO" ]; then
 		echo "WARNING: relaunching as $RUNAS" >&2
-		_cmd=("$RUNUSER" "-u" "$RUNAS" -- "$0" "${INCOMING_ARGS[@]}");
+		_cmd=("$SUDO" "-u" "$RUNAS" "$0" "${INCOMING_ARGS[@]}");
 		exec "${_cmd[@]}"
 	fi
-	echo "ERROR: you should run this script as ${RUNAS}, not '${myuser}'." >&2
-    echo "       To correct this, try 'sudo -u $RUNAS $0 $@'" >&2
-	echo "       If you wish for OpenNMS to run as ${myuser} instead," >&2
-	echo "       create or edit ${OPENNMS_HOME}/etc/opennms.conf and set 'RUNAS=${myuser}'" >&2
+	echo "ERROR: you must run this script as ${RUNAS}, not '${myuser}'." >&2
+	echo "       Create or edit ${OPENNMS_HOME}/etc/opennms.conf and set 'RUNAS=${myuser}'" >&2
+	echo "       if you wish for OpenNMS to run as ${myuser} instead." >&2
 	echo "       If you have already edited opennms.conf, make sure that 'User=' is also set" >&2
 	echo "       in the OpenNMS systemd service." >&2
 	exit 4 # According to LSB: 4 - user had insufficient privileges
diff --git a/opennms-base-assembly/src/main/filtered/bin/runjava b/opennms-base-assembly/src/main/filtered/bin/runjava
--- a/opennms-base-assembly/src/main/filtered/bin/runjava
+++ b/opennms-base-assembly/src/main/filtered/bin/runjava
@@ -53,17 +53,14 @@ if [ -e "${opennms_home}/bin/_lib.sh" ]; then
         __onms_read_conf "${opennms_home}/etc/opennms.conf"
     fi
 
-    RUNUSER="$(command -v runuser 2>/dev/null || which runuser 2>/dev/null || :)"
+    SUDO="$(command -v sudo 2>/dev/null || which sudo 2>/dev/null || :)"
     myuser="$(id -u -n)"
     if [ "$myuser" != "$RUNAS" ]; then
-        if [ "$myuser" = "root" ] && [ -x "$RUNUSER" ]; then
-            _cmd=("$RUNUSER" "-u" "$RUNAS" -- "$0" "${INCOMING_ARGS[@]}");
+        if [ "$myuser" = "root" ] && [ -n "$SUDO" ] && [ -x "$SUDO" ]; then
+            _cmd=("$SUDO" "-u" "$RUNAS" "$0" "${INCOMING_ARGS[@]}");
             exec "${_cmd[@]}"
         fi
-        echo "ERROR: you should run this script as ${RUNAS}, not '${myuser}'." >&2
-        echo "       To correct this, try 'sudo -u ${RUNAS} $0 $@'" >&2
-        echo "       If you wish for OpenNMS to run as ${myuser} instead," >&2
-        echo "       create or edit ${OPENNMS_HOME}/etc/opennms.conf and set 'RUNAS=${myuser}'." >&2
+        echo "ERROR: you must run this script as ${RUNAS}, not '${myuser}'." >&2
         exit 4 # According to LSB: 4 - user had insufficient privileges
     fi
 fi
@@ -304,6 +301,16 @@ checkJavaHome() {
     fi
 }
 
+get_real_path_if_possible() {
+    unresolved="$1"
+    readlink="$(command -v readlink 2>/dev/null)"
+    if [ -n "$readlink" ] && [ -n "$unresolved" ] && [ -x "$unresolved" ]; then
+        "$readlink" "$unresolved" || echo "$unresolved"
+    else
+        echo "$unresolved"
+    fi
+}
+
 
 #
 # Function: checkPath()
@@ -318,7 +325,7 @@ checkPath() {
 
     readlink="$(command -v readlink 2>/dev/null)"
     if [ -n "$readlink" ] && [ -n "$JP" ]; then
-        JP="$(readlink -f "$JP")"
+        JP="$(readlink "$JP")"
     fi
 
     if [ -n "$JP" ]; then
