NMS-10518: a number of changes to facilitate unit testing
* getPid now validates that the pid returned is a positive integer
* running commands is now wrapped in `runCmd` and (almost) all
  checks for the dry-run (-n) option are done there
* support was added to `doStatus` to shortcut the status returned
  so unit tests can simulate running/not-running

diff --git a/opennms-base-assembly/src/main/filtered/bin/opennms b/opennms-base-assembly/src/main/filtered/bin/opennms
--- a/opennms-base-assembly/src/main/filtered/bin/opennms
+++ b/opennms-base-assembly/src/main/filtered/bin/opennms
@@ -82,6 +82,9 @@ HOTSPOT=""
 # Enable verbose garbage collection debugging.
 VERBOSE_GC=""
 
+# Whether we're in the test framework
+OPENNMS_UNIT_TEST=0
+
 # Additional options to pass to runjava.
 RUNJAVA_OPTIONS=()
 
@@ -160,8 +163,20 @@ END
 	return
 }
 
+isRunning() {
+	[ "$(/bin/ps -o pid= -o comm= -p "$1" | wc -l)" -gt 0 ];
+}
+
 getPid(){
-	test -f "$OPENNMS_PIDFILE" && cat "$OPENNMS_PIDFILE"
+	__pid=""
+	if [ -f "$OPENNMS_PIDFILE" ]; then
+		__pid="$(cat "$OPENNMS_PIDFILE")"
+	fi
+	if [[ "$__pid" =~ ^[0-9]+$ ]] && [ "$__pid" -gt 0 ]; then
+		echo "$__pid"
+		return
+	fi
+	echo -1
 }
 
 getTempFile(){
@@ -216,7 +231,7 @@ checkXmlFiles(){
 		if grep "non-ip-snmp-primary" "$FILE" >/dev/null 2>&1 || grep "non-ip-interfaces" "$FILE" >/dev/null 2>&1; then
 			echo "$FILE" >&2
 		fi
-	done >"$TEMPFILE" 2>&1
+	done >/dev/null 2>"$TEMPFILE"
 
 	FAILCOUNT="$(wc -l < "$TEMPFILE")"
 	if [ "$FAILCOUNT" -gt 0 ]; then
@@ -288,6 +303,14 @@ checkLogDir(){
 	return 0
 }
 
+runCmd(){
+	if [ "$NOEXECUTE" -eq 1 ]; then
+		echo "Skipping execution:" "$@"
+	else
+		"$@"
+	fi
+}
+
 doStart(){
 	checkXmlFiles || return $?
 	checkRpmFiles || return $?
@@ -321,7 +344,7 @@ doStart(){
 	esac
 
 
-	if ! "${JAVA_CMD[@]}" "-Dopennms.home=$OPENNMS_HOME" -jar "$BOOTSTRAP" check; then
+	if [ "$NOEXECUTE" -eq 0 ] && ! "${JAVA_CMD[@]}" "-Dopennms.home=$OPENNMS_HOME" -jar "$BOOTSTRAP" check; then
 		echo "${install.package.description} was unable to connect to the 'opennms' database configured in opennms-datasources.xml." >&2
 		return 1
 	fi
@@ -365,26 +388,23 @@ doStart(){
 		APP_VM_PARMS=("-Dorg.apache.jasper.compiler.disablejsr199=true" "${APP_VM_PARMS[@]}")
 	fi
 
-	if [ "$NOEXECUTE" -eq 0 ]; then
-		CMD=("${JAVA_CMD[@]}" "-Djava.endorsed.dirs=$OPENNMS_HOME/lib/endorsed" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}")
-		if [ "$BACKGROUND" = 1 ]; then
-			# shellcheck disable=SC2129
-			echo "------------------------------------------------------------------------------" >> "$REDIRECT"
-			date >> "$REDIRECT"
-			echo "begin ulimit settings:" >> "$REDIRECT"
-			ulimit -a >> "$REDIRECT"
-			echo "end ulimit settings" >> "$REDIRECT"
-			echo "Executing command:" "${CMD[@]}" >> "$REDIRECT"
-			"${CMD[@]}" >>"$REDIRECT" 2>&1 &
-			OPENNMS_PID=$!
-			echo $OPENNMS_PID > "$OPENNMS_PIDFILE"
-		else
-			echo "running ulimit -a"
-			ulimit -a
-			echo "Executing command:" "${CMD[@]}"
-			"${CMD[@]}"
-			exit $?
-		fi
+	CMD=("${JAVA_CMD[@]}" "-Djava.endorsed.dirs=$OPENNMS_HOME/lib/endorsed" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}")
+	if [ "$BACKGROUND" = 1 ]; then
+		# shellcheck disable=SC2129
+		echo "------------------------------------------------------------------------------" >> "$REDIRECT"
+		date >> "$REDIRECT"
+		echo "begin ulimit settings:" >> "$REDIRECT"
+		ulimit -a >> "$REDIRECT"
+		echo "end ulimit settings" >> "$REDIRECT"
+		echo "Executing command:" "${CMD[@]}" >> "$REDIRECT"
+		runCmd "${CMD[@]}" >>"$REDIRECT" 2>&1 &
+		OPENNMS_PID=$!
+		echo $OPENNMS_PID > "$OPENNMS_PIDFILE"
+	else
+		echo "running ulimit -a"
+		ulimit -a
+		runCmd "${CMD[@]}"
+		exit $?
 	fi
 
 	if [ "$START_TIMEOUT" -eq 0 ]; then
@@ -399,7 +419,7 @@ doStart(){
 		if doStatus "$@"; then
 			return 0
 		fi
-		if /bin/ps -p $OPENNMS_PID | grep "^ *$OPENNMS_PID " > /dev/null; then
+		if isRunning "$OPENNMS_PID"; then
 			true		# Java process is still running... don't do anything
 		else
 			echo "Started ${install.package.description}, but it stopped running: for details see $REDIRECT" >&2
@@ -417,7 +437,7 @@ doPause(){
 	if doStatus "$@"; then
 		# If there is a PID file for OpenNMS, specify the PID
 		PID="$(getPid)"
-		if [ x"$PID" != x"" ]; then
+		if [ "$PID" -gt 0 ]; then
 			PARM_PID=("-p" "$PID")
 		else
 			PARM_PID=()
@@ -428,9 +448,7 @@ doPause(){
 		if [ -n "$SERVICE" ]; then
 			APP_PARMS_BEFORE+=("$SERVICE")
 		fi
-		if [ "$NOEXECUTE" -eq 0 ]; then
-			"${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
-		fi
+		runCmd "${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
 	else
 		echo "${install.package.description} is not running." >&2
 	fi
@@ -440,7 +458,7 @@ doResume(){
 	if doStatus "$@"; then
 		# If there is a PID file for OpenNMS, specify the PID
 		PID="$(getPid)"
-		if [ x"$PID" != x"" ]; then
+		if [ "$PID" -gt 0 ]; then
 			PARM_PID=("-p" "$PID")
 		else
 			PARM_PID=()
@@ -451,9 +469,7 @@ doResume(){
 		if [ -n "$SERVICE" ]; then
 			APP_PARMS_BEFORE+=("$SERVICE")
 		fi
-		if [ "$NOEXECUTE" -eq 0 ]; then
-			"${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
-		fi
+		runCmd "${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
 	else
 		echo "${install.package.description} is not running." >&2
 	fi
@@ -474,14 +490,16 @@ doCheck() {
 doStop() {
 	doStatus "$@"
 	if [ "$?" -eq 3 ]; then
-		echo "Trying to stop ${install.package.description} but it's already stopped." >&2
+		(sleep 1; echo "Trying to stop ${install.package.description} but it's already stopped." >&2)
 		return 0   # LSB says: stopping when stopped is successful
 	fi
 
-	pid="$(getPid)"
-	if [ -n "$pid" ]; then
+	PID="$(getPid)"
+	if [ "$PID" -gt 0 ]; then
 		echo "=== ${install.package.description} Complimentary Thread Dump ===" >> "$REDIRECT"
-		kill -3 "$pid" >> "$REDIRECT" 2>&1
+		kill -3 "$PID" >> "$REDIRECT" 2>&1
+	else
+		echo "=== WARNING: Unable to Perform Complimentary Thread Dump ===" >> "$REDIRECT"
 	fi
 
 	STATUS_ATTEMPTS=0
@@ -494,20 +512,18 @@ doStop() {
 
 		# If there is a PID file for OpenNMS, specify the PID
 		PID="$(getPid)"
-		if [ x"$PID" != x"" ]; then
+		if [ "$PID" -gt 0 ]; then
 			PARM_PID=("-p" "$PID")
 		else
 			PARM_PID=()
 		fi
 
-		if [ "$NOEXECUTE" -eq 0 ]; then
-			APP_VM_PARMS=("${CONTROLLER_OPTIONS[@]}")
-			APP_PARMS_BEFORE=("${PARM_PID[@]}" -u "$JMX_URL" stop)
-			if [ -n "$SERVICE" ]; then
-				APP_PARMS_BEFORE+=("$SERVICE")
-			fi
-			"${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
+		APP_VM_PARMS=("${CONTROLLER_OPTIONS[@]}")
+		APP_PARMS_BEFORE=("${PARM_PID[@]}" -u "$JMX_URL" stop)
+		if [ -n "$SERVICE" ]; then
+			APP_PARMS_BEFORE+=("$SERVICE")
 		fi
+		runCmd "${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
 
 		sleep $STATUS_WAIT
 		((STATUS_ATTEMPTS++))
@@ -520,7 +536,7 @@ doKill(){
 	if doStatus "$@"; then
 		# If there is a PID file for OpenNMS, specify the PID
 		PID="$(getPid)"
-		if [ x"$PID" != x"" ]; then
+		if [ "$PID" -gt 0 ]; then
 			PARM_PID=("-p" "$PID")
 		else
 			PARM_PID=()
@@ -528,13 +544,13 @@ doKill(){
 
 		APP_VM_PARMS=("${CONTROLLER_OPTIONS[@]}")
 		APP_PARMS_BEFORE=("${PARM_PID[@]}" -u "$JMX_URL" exit)
-		"${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
+		runCmd "${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
 	fi
 
-	pid="$(getPid)"
-	if [ x"$pid" != x"" ]; then
-		if [ "$(/bin/ps -p "$pid" 2>/dev/null | wc -l 2>/dev/null)" -gt 0 ]; then
-			kill -9 "$pid" > /dev/null 2>&1
+	PID="$(getPid)"
+	if [ "$PID" -gt 0 ]; then
+		if isRunning "$PID"; then
+			kill -9 "$PID" > /dev/null 2>&1
 			return $?
 		fi
 	fi
@@ -544,6 +560,11 @@ doKill(){
 }
 
 doStatus(){
+	if [ $OPENNMS_UNIT_TEST -eq 1 ] && [ -n "$OPENNMS_UNIT_TEST_STATUS" ]; then
+		eval "return $OPENNMS_UNIT_TEST_STATUS"
+		return $?
+	fi
+
 	if [ "$VERBOSE" -gt 0 ]; then
 		PARM_VERBOSE=("-v")
 	else
@@ -552,17 +573,15 @@ doStatus(){
 
 	# If there is a PID file for OpenNMS, specify the PID
 	PID="$(getPid)"
-	if [ x"$PID" != x"" ]; then
+	if [ "$PID" -gt 0 ]; then
 		PARM_PID=("-p" "$PID")
 	else
 		PARM_PID=()
 	fi
 
-	if [ "$NOEXECUTE" -eq 0 ]; then
-		APP_VM_PARMS=("${CONTROLLER_OPTIONS[@]}")
-		APP_PARMS_BEFORE=("${PARM_PID[@]}" -u "$JMX_URL" "${PARM_VERBOSE[@]}" status)
-		"${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
-	fi
+	APP_VM_PARMS=("${CONTROLLER_OPTIONS[@]}")
+	APP_PARMS_BEFORE=("${PARM_PID[@]}" -u "$JMX_URL" "${PARM_VERBOSE[@]}" status)
+	runCmd "${JAVA_CMD[@]}" "${APP_VM_PARMS[@]}" -jar "$BOOTSTRAP" "${APP_PARMS_CONTROLLER[@]}" "${APP_PARMS_BEFORE[@]}" "$@" "${APP_PARMS_AFTER[@]}"
 }
 
 FUNCTIONS_LOADED=0
@@ -856,8 +875,15 @@ case "$COMMAND" in
 	restart)
 		## Stop the service and regardless of whether it was
 		## running or not, start it again.
-		"$OPENNMS_HOME/bin/opennms" stop && \
-		"$OPENNMS_HOME/bin/opennms" start
+		__opennms_cmd=("$OPENNMS_HOME/bin/opennms");
+		if [ "$NOEXECUTE" -eq 1 ]; then
+			__opennms_cmd+=("-n")
+		fi
+		if [ "$BACKGROUND" -eq 0 ]; then
+			__opennms_cmd+=("-f")
+		fi
+		"${__opennms_cmd[@]}" "stop" && \
+		"${__opennms_cmd[@]}" "start"
 		;;
 
 	status)
