NMS-6068 fix opennms status return code when not configured

diff --git a/opennms-base-assembly/src/main/filtered/bin/opennms b/opennms-base-assembly/src/main/filtered/bin/opennms
--- a/opennms-base-assembly/src/main/filtered/bin/opennms
+++ b/opennms-base-assembly/src/main/filtered/bin/opennms
@@ -94,6 +94,8 @@ MAXIMUM_FILE_DESCRIPTORS=20480
 # maximum size of stack segment (in kbytes) to be setted by ulimit -s
 MAXIMUM_SIZE_STACK_SEGMENT=8192
 
+COMMAND=""
+
 #### ------------> DO NOT CHANGE VARIABLES IN THIS FILE <------------- ####
 #### Create $OPENNMS_HOME/etc/opennms.conf and put overrides in there. ####
 #### ------------> DO NOT CHANGE VARIABLES IN THIS FILE <------------- ####
@@ -171,7 +173,16 @@ checkXmlFiles(){
 		rm "$TEMPFILE"
 		if [ $FAILCOUNT -gt 0 ]; then
 			echo "Validation failed on $FAILCOUNT XML files.  Exiting." >&2
-			return 6	# From LSB: 6 - program is not configured
+			case $COMMAND in
+				status)
+					# when calling `opennms status` return 3 for "stopped"
+					return 3	# From LSB: 3 - program is stopped
+					;;
+				*)
+					# any other init command should return 6 on error
+					return 6	# From LSB: 6 - program is not configured
+					;;
+			esac
 		fi
 	fi
 		 
@@ -201,7 +212,16 @@ up-to-date and delete any leftover .$EXTENSION files or
 OpenNMS will not start.
 
 END
-			return 6	# From LSB: 6 - program is not configured
+			case $COMMAND in
+				status)
+					# when calling `opennms status` return 3 for "stopped"
+					return 3	# From LSB: 3 - program is stopped
+					;;
+				*)
+					# any other init command should return 6 on error
+					return 6	# From LSB: 6 - program is not configured
+					;;
+			esac
 		fi
 	done
 
@@ -614,7 +634,17 @@ For details, see the install guide at:
 http://www.opennms.org/index.php/QuickStart#Initialize_OpenNMS_and_the_Database
 
 END
-	exit 6	# From LSB: 6 - program is not configured
+
+	case $COMMAND in
+		status)
+			# when calling `opennms status` return 3 for "stopped"
+			exit 3	# From LSB: 3 - program is stopped
+			;;
+		*)
+			# any other init command should return 6 on error
+			exit 6	# From LSB: 6 - program is not configured
+			;;
+	esac
 fi
 
 myuser="`id | sed -e 's/uid=[0-9][0-9]*(//' -e 's/).*//'`"
