break OCI bits out into commands

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -183,13 +183,8 @@ commands:
             sudo swapon /swapfile
             sudo sysctl vm.swappiness=5
             cat /proc/sys/vm/swappiness
-      - restore-workflow-assets:
-          cache_prefix: oci-horizon
-      - run:
-          name: Load Horizon OCI image
-          command: |
-            cd opennms-container/horizon
-            docker image load -i /tmp/oci-horizon/container.oci
+      - load-oci:
+          key: horizon
       - run:
           name: Monitor JVM processes
           background: true
@@ -366,7 +361,7 @@ commands:
         description: the cache prefix
         type: string
       source_path:
-        description: the source path to cache
+        description: the source directory to cache
         type: string
     steps:
       - run:
@@ -386,7 +381,7 @@ commands:
         description: the cache prefix
         type: string
       target_path:
-        description: the target path to restore into
+        description: the target directory to restore into
         type: string
         default: ""
     steps:
@@ -402,6 +397,38 @@ commands:
                   SOURCE_PATH="/tmp/<< parameters.cache_prefix >>"
                   mkdir -p "<< parameters.target_path >>"
                   rsync -ar "${SOURCE_PATH}/" "$(echo "<< parameters.target_path >>" | sed -e 's,/*$,,')/"
+  cache-oci:
+    parameters:
+      key:
+        description: the cache key for storing the OCI
+        type: string
+      path:
+        description: the path to the directory containing the OCI
+        type: string
+    steps:
+      - cache-workflow-assets:
+          cache_prefix: oci-<< parameters.key >>
+          source_path: << parameters.path >>
+  load-oci:
+    parameters:
+      key:
+        description: the OCI cache key to restore
+        type: string
+    steps:
+      - restore-workflow-assets:
+          cache_prefix: oci-<< parameters.key >>
+      - run:
+          name: Load Docker Image(s) in oci-<< parameters.key >>
+          command: |
+            cd "/tmp/oci-<< parameters.key >>"
+            if [ "$(ls -1 *.oci | wc -l)" -eq 0 ]; then
+              echo "ERROR: No OCI files to load. Something probably went wrong earlier."
+              exit 1
+            fi
+            for FILE in *.oci; do
+              echo "Loading ${FILE} into Docker..."
+              docker image load -i "$FILE"
+            done
 
 workflows:
   weekly-coverage:
@@ -577,9 +604,9 @@ jobs:
       - cache-workflow-assets:
           cache_prefix: rpm-horizon
           source_path: target/rpm/RPMS/noarch
-      - cache-workflow-assets:
-          cache_prefix: oci-horizon
-          source_path: opennms-container/horizon/images/
+      - cache-oci:
+          key: horizon
+          path: opennms-container/horizon/images/
   horizon-deb-build:
     executor: debian-build-executor
     resource_class: large
@@ -636,16 +663,15 @@ jobs:
     executor: centos-build-executor
     steps:
       - cached-checkout
-      - restore-workflow-assets:
-          cache_prefix: oci-horizon
       - setup_remote_docker:
           docker_layer_caching: true
       - dockerhub-login
+      - load-oci:
+          key: horizon
       - run:
-          name: Load Horizon OCI image, tag it and publish to registry
+          name: tag horizon Docker image and publish to registry
           command: |
             cd opennms-container/horizon
-            docker image load -i /tmp/oci-horizon/container.oci
             ./tag.sh
             ./publish.sh
   integration-test:
