eval is evaluated at make time :P

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -263,8 +263,7 @@ install: build
 	## Make sure there aren't any files left over in debian/temp that missed packaging
 	##
 	find debian/temp -name .gitignore -o -name .gwtignore -o -name .readme -exec rm -rf {} \;
-	$(eval REMAINING_COUNT := $(shell find debian/temp -type f | wc -l))
-	if [ $(REMAINING_COUNT) -gt 0 ]; then echo "FAILED, files in debian/temp that have not been packaged:"; find debian/temp -type f; exit 1; fi
+	if [ `find debian/temp -type f | wc -l` -gt 0 ]; then echo "FAILED, files in debian/temp that have not been packaged:"; find debian/temp -type f; exit 1; fi
 
 # Build architecture-independent files here.
 binary-indep: build install
