Merged revisions 10468,10472 via svnmerge from https://opennms.svn.sourceforge.net/svnroot/opennms/opennms/branches/1.6-testing
................
  r10468 | rangerrick | 2008-09-10 10:55:57 -0400 (Wed, 10 Sep 2008) | 1 line
  
  stuff that is right in 1.6-release and not in testing
................
  r10472 | PaulSD | 2008-09-10 13:31:39 -0400 (Wed, 10 Sep 2008) | 9 lines
  
  Merged revisions 10471 via svnmerge from
  https://opennms.svn.sourceforge.net/svnroot/opennms/opennms/trunk
  
  ........
    r10471 | PaulSD
  
    Unbreak logging in Tomcat
    See Bug 2615
  ........
................

diff --git a/opennms-daemon/src/main/filtered/bin/opennms b/opennms-daemon/src/main/filtered/bin/opennms
--- a/opennms-daemon/src/main/filtered/bin/opennms
+++ b/opennms-daemon/src/main/filtered/bin/opennms
@@ -157,14 +157,14 @@ checkXmlFiles(){
 				echo "ERROR: XML validation failed: $FILE"
 				echo "	   run '$XMLLINT $FILE' for details"
 			fi
-			done >"$TEMPFILE"
-			cat "$TEMPFILE"
-			FAILCOUNT=`cat "$TEMPFILE" | grep -c 'XML validation failed'`
-			rm "$TEMPFILE"
-			if [ $FAILCOUNT -gt 0 ]; then
-				echo "Validation failed on $FAILCOUNT XML files.  Exiting."
-				exit 1
-			fi
+		done >"$TEMPFILE"
+		cat "$TEMPFILE"
+		FAILCOUNT=`cat "$TEMPFILE" | grep -c 'XML validation failed'`
+		rm "$TEMPFILE"
+		if [ $FAILCOUNT -gt 0 ]; then
+			echo "Validation failed on $FAILCOUNT XML files.  Exiting."
+			exit 1
+		fi
 	fi
 		 
 	return 0
