Tweak CircleCI scripts to use new opennms/* tags

diff --git a/.circleci/main/commands/oci/oci.yml b/.circleci/main/commands/oci/oci.yml
--- a/.circleci/main/commands/oci/oci.yml
+++ b/.circleci/main/commands/oci/oci.yml
@@ -23,14 +23,20 @@ commands:
 
             for FILE in *.oci; do
               echo "Loading ${FILE} into Docker..."
-              _tag="$(printf "${FILE}" | sed -e 's,\.oci$,,'):latest"
+              _tag="opennms/$(printf "${FILE}" | sed -e 's,\.oci$,,'):latest"
               if [ -z "$(docker image ls -q "${_tag}")" ]; then
+                echo "Didn't find existing image '${_tag}' -- loading from ${FILE}"
                 docker image load -i "${FILE}"
+              fi
+              if [ -z "$(docker image ls -q "${_tag}")" ]; then
+                echo "ERROR: After loading ${FILE} we still don't have an image with tag '${_tag}'; see 'docker image ls' output following"
+                docker image ls
+                exit 1
               fi
               _unprefixed="$(echo "${_tag}" | cut -d/ -f2 | cut -d- -f1)"
               echo "Tagging docker image ${_tag} as [opennms/]${_unprefixed}:latest"
               docker image tag "${_tag}" "opennms/${_unprefixed}:latest"
-              docker image tag "${_tag}" "${_unprefixed}:latest"
+              echo "NO LONGER TAGGING docker image as ${_unprefixed}:latest WITHOUT opennms/"
             done
 
   build-image-single-arch:
@@ -65,7 +71,7 @@ commands:
             export TAG="<< parameters.container_name >>-${ARCH}"
             make DOCKER_ARCH="<< parameters.architecture >>" \
                  DOCKER_OCI="images/${TAG}.oci" \
-                 DOCKER_TAG="${TAG}" \
+                 DOCKER_TAG="opennms/${TAG}" \
                  BUILD_NUMBER="${CIRCLE_BUILD_NUM}" \
                  BUILD_URL="${CIRCLE_BUILD_URL}" \
                  BUILD_BRANCH="${CIRCLE_BRANCH}" \
