fix pidfile handling

diff --git a/features/remote-poller-standalone/src/main/filtered/remote-poller.init b/features/remote-poller-standalone/src/main/filtered/remote-poller.init
--- a/features/remote-poller-standalone/src/main/filtered/remote-poller.init
+++ b/features/remote-poller-standalone/src/main/filtered/remote-poller.init
@@ -103,14 +103,16 @@ case "$1" in
 
 		echo -n "Starting $DESC: "
 		if [ -x /sbin/start-stop-daemon ]; then
-			start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE $CHUID --startas /usr/sbin/opennms-remote-poller -- $JVM_ARGS -u "$URI" -l "$LOCATION" $EXTRA_ARGS >/dev/null
+			start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --make-pidfile $CHUID --startas $OPENNMS_HOME/bin/remote-poller.sh -- $JVM_ARGS -u "$URI" -l "$LOCATION" $EXTRA_ARGS >/dev/null
 		else
-			$SUDO_PREFIX $OPENNMS_HOME/bin/remote-poller.sh $JVM_ARGS -u "$URI" -l "$LOCATION" $EXTRA_ARGS >/dev/null
-			RETVAL="$?"
-			POLLER_PID="$!"
-			echo "$POLLER_PID" > "$PIDFILE"
-			echo "OK"
-			exit 0
+			if $SUDO_PREFIX $OPENNMS_HOME/bin/remote-poller.sh $JVM_ARGS -u "$URI" -l "$LOCATION" $EXTRA_ARGS >/dev/null; then
+				echo "OK"
+				exit 0
+			else
+				RETVAL="$?"
+				echo "FAILED"
+				exit $RETVAL
+			fi
 		fi
 		echo "."
 		;;
