Pull the contents of runjava into the %pre script in opennms.spec and effectively do a "runjava -s -q -n" to make sure that we have a good JRE before trying to install.
XXX UNTESTED, but I'll get to that soon XXX

diff --git a/tools/packages/opennms/opennms.spec.in b/tools/packages/opennms/opennms.spec.in
--- a/tools/packages/opennms/opennms.spec.in
+++ b/tools/packages/opennms/opennms.spec.in
@@ -372,6 +372,25 @@ rm -rf $RPM_BUILD_ROOT
 
 %pre
 
+@runjava.contents@
+
+# Do the equivalent to: %{instprefix}/bin/runjava -q -s -n
+
+# quiet mode, "-q"
+exec 3>/dev/null
+
+# dryrun mode, "-n"
+dryrun=1
+
+# search mode, "-s"
+setupJava
+if [ $? -ne 0 ]; then
+    echo "A suitable Java Runtime Environment could not be found." >&2
+    echo "Please set and export the JAVA_HOME environment variable to" >&2
+    echo "point where your JDK is installed." >&2
+    exit 1
+fi
+
 %post
 
 echo -e "- executing runjava to choose a Java Runtime Environment... \c"
diff --git a/tools/run/runjava b/tools/run/runjava
--- a/tools/run/runjava
+++ b/tools/run/runjava
@@ -35,6 +35,7 @@
 
 opennms_home="@install.dir@"
 searchdirs="/usr /opt /Library"
+dryrun=0
 
 java_conf="$opennms_home/etc/java.conf"
 basename="`basename $0`"
@@ -345,93 +346,96 @@ saveJava() {
     return 0
 }
 
-exclusive=0
+parseArgsAndDoStuff() {
+    exclusive=0
+    
+    check=0
+    force=""
+    quiet=0
+    run=0
+    search=0
+    
+    while getopts cf:hnqrs c
+    do
+      case $c in
+          c)
+    	  check=1
+    	  exclusive=`expr $exclusive + 1`
+    	  ;;
+    
+          f)
+    	  force="$OPTARG"
+    	  exclusive=`expr $exclusive + 1`
+    	  ;;
+    
+          h)
+    	  printHelp
+    	  exit 0
+    	  ;;
+    
+          n)
+    	  dryrun=1
+    	  ;;
+    
+          q)
+    	  quiet=1
+    	  ;;
+    
+          r)
+    	  run=1
+    	  exclusive=`expr $exclusive + 1`
+    	  ;;
+    
+          s)
+    	  search=1
+    	  exclusive=`expr $exclusive + 1`
+    	  ;;
+    
+          \?)
+              die "Invalid option.  Use \"-h\" for help."
+    	  ;;
+      esac
+    done
+    shift `expr $OPTIND - 1`
+    
+    if [ $exclusive -eq 0 ]; then
+        warn "You must choose one of the command-line options."
+        die "Use \"-h\" for help."
+    fi
+    
+    if [ $exclusive -gt 1 ]; then
+        warn "You must choose only one of the command-line options."
+        die "Use \"-h\" for help."
+    fi
+    
+    if [ $quiet -gt 0 ]; then
+        exec 3>/dev/null
+    else
+        exec 3>&1
+    fi
+    
+    if [ $check -gt 0 ]; then
+        checkConfiguredJava
+        exit $?
+    fi
+    
+    if [ x"$force" != x"" ]; then
+        JP="$force"
+        forceJava
+        exit $?
+    fi
+    
+    if [ $run -gt 0 ]; then
+        runJava "$@"
+        exit $?
+    fi
+    
+    if [ $search -gt 0 ]; then
+        setupJava
+        exit $?
+    fi
+    
+    die "internal error... got to end of script and shouldn't have"
+}
 
-check=0
-force=""
-dryrun=0
-quiet=0
-run=0
-search=0
-
-while getopts cf:hnqrs c
-do
-  case $c in
-      c)
-	  check=1
-	  exclusive=`expr $exclusive + 1`
-	  ;;
-
-      f)
-	  force="$OPTARG"
-	  exclusive=`expr $exclusive + 1`
-	  ;;
-
-      h)
-	  printHelp
-	  exit 0
-	  ;;
-
-      n)
-	  dryrun=1
-	  ;;
-
-      q)
-	  quiet=1
-	  ;;
-
-      r)
-	  run=1
-	  exclusive=`expr $exclusive + 1`
-	  ;;
-
-      s)
-	  search=1
-	  exclusive=`expr $exclusive + 1`
-	  ;;
-
-      \?)
-          die "Invalid option.  Use \"-h\" for help."
-	  ;;
-  esac
-done
-shift `expr $OPTIND - 1`
-
-if [ $exclusive -eq 0 ]; then
-    warn "You must choose one of the command-line options."
-    die "Use \"-h\" for help."
-fi
-
-if [ $exclusive -gt 1 ]; then
-    warn "You must choose only one of the command-line options."
-    die "Use \"-h\" for help."
-fi
-
-if [ $quiet -gt 0 ]; then
-    exec 3>/dev/null
-else
-    exec 3>&1
-fi
-
-if [ $check -gt 0 ]; then
-    checkConfiguredJava
-    exit $?
-fi
-
-if [ x"$force" != x"" ]; then
-    JP="$force"
-    forceJava
-    exit $?
-fi
-
-if [ $run -gt 0 ]; then
-    runJava "$@"
-    exit $?
-fi
-
-if [ $search -gt 0 ]; then
-    setupJava
-    exit $?
-fi
-
-die "internal error... got to end of script and shouldn't have"
+parseArgsAndDoStuff "$@"	### CHOMP ME
