Removed chkconfig testing from %pre and added some warnings to %post if chkconfig doesn't configure OpenNMS correctly.  OpenNMS will install but will not be configured to automagically startup.-David

diff --git a/tools/packages/opennms/opennms.spec.in b/tools/packages/opennms/opennms.spec.in
--- a/tools/packages/opennms/opennms.spec.in
+++ b/tools/packages/opennms/opennms.spec.in
@@ -351,25 +351,6 @@ rm -rf $RPM_BUILD_ROOT
 
 %pre
 
-if [ -x /sbin/chkconfig ]; then
-    chkconfig="/sbin/chkconfig"
-elif [ -x "`which chkconfig 2>&1`" ]; then
-    chkconfig="`which chkconfig 2>&1`"
-else
-    chkconfig=""
-fi
-
-if [ x"$chkconfig" != x"" -a -f %{initdir}/init.d/%{psql_service} ]; then
-    $chkconfig %{psql_service} | grep 'on$' > /dev/null
-    if [ $? -ne 0 ]; then
-	echo "'$chkconfig %{psql_service}' shows that the PostgreSQL" >&2
-	echo "server is not configured to start automatically at boot" >&2
-	echo "time.  You must run '$chkconfig --add %{psql_service}'" >&2
-	echo "before installing OpenNMS." >&2
-	exit 1
-    fi
-fi
-
 %post
 
 echo -e "- executing runjava to choose a Java Runtime Environment... \c"
@@ -401,13 +382,29 @@ echo "done"
 
 # add the OpenNMS init
 
-echo -e "- adding OpenNMS init script using 'chkconfig'... \c"
 if [ -x /sbin/chkconfig ]; then
-    /sbin/chkconfig --add opennms > /dev/null
+    chkconfig="/sbin/chkconfig"
+elif [ -x "`which chkconfig 2>&1`" ]; then
+    chkconfig="`which chkconfig 2>&1`"
 else
-    if [ -x `which chkconfig 2>&1` ]; then
-	`which chkconfig` --add opennms > /dev/null
+    chkconfig=""
+fi
+
+echo -e "- adding OpenNMS init script using 'chkconfig'... \c"
+if [ -n "$chkconfig" ]; then
+    if $chkconfig --add opennms > /dev/null; then 
+       echo "done"
+    else
+       echo "Warn: Couldn't add OpenNMS to init scripts." >&2
+       echo "      To make OpenNMS startup automatically," >&2
+       echo "      resolve these errors.  Consult the chkconfig" >&2
+       echo "      man pages.  If you are using insserv, this maybe" >&2
+       echo "      a postgresql dependency problem." >&2
     fi
+else
+    echo "Warn: Couldn't find the chkconfig script to configure" >&2
+    echo "      OpenNMS to start automatically.  You'll need to" >&2
+    echo "      configure this your self." >&2
 fi
 echo "done"
 
